'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ja';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
    en: {
        'navigation.home': 'HOME',
        'navigation.engineers': 'List Engineer',
        'navigation.services': 'Service',
        'navigation.contact': 'Contact us',
        'navigation.login': 'Login',
        'hero.whatWeDo': 'What We Do',
        'hero.ourService': 'Our Service',
        'hero.englishText1': 'A reliable Vietnam offshore development partner for your project.',
        'hero.englishText2': 'Build faster, smarter, and more cost-effective with our expert team.',
        'hero.japaneseText1': 'A reliable Vietnam offshore development partner for your project.',
        'hero.japaneseText2': 'Build faster, smarter, and more cost-effective with our expert team.',
        'hero.ctaButton': 'Contact us →',
        'introduction.title': 'SKILL BRIDGE',
        'introduction.subtitle': 'A Bridge Connecting Japanese Companies and Vietnamese IT Talent A Platform that Supports Challenges',
        'introduction.description1': 'SkillBridge is a business matching service specialized in offshore development in Vietnam. In Japan, hiring engineers is becoming increasingly difficult, and companies are struggling to secure skilled talent.',
        'introduction.description2': 'Through collaboration with experienced Vietnamese engineers, SkillBridge provides high-quality IT talent while significantly reducing costs.',
        'introduction.description3': 'We aim to solve the serious issue of IT talent shortages in Japanese companies and create a future where working with global talent is a natural part of every business.',
        'merits.title': '- Merit -',
        'merits.subtitle': 'To facilitate the future development of Japan The benefits provided by SKILL BRIDGE',
        'merits.merit1.title': 'Assign Top Talent',
        'merits.merit1.description': 'We can assign highly skilled engineers who specialize in specific fields such as AI, blockchain, and mobile app development.',
        'merits.merit1.benefits': 'By securing experienced developers and BrSE, we ensure smooth project progress and deliver outstanding results.',
        'merits.merit2.title': 'Cost Efficiency without Quality Trade-off',
        'merits.merit2.description': 'Significant cost savings compared to domestic development (30-50% reduction).',
        'merits.merit2.benefits': 'Access to high-quality talent at competitive rates. Transparent cost management with clear contract structure (MSA + Sub-contract), making it easy to scale resources as needed.',
        'merits.merit3.title': 'Smooth Communication & Flexible Engagement',
        'merits.merit3.description': 'Supported by Bridge SEs and a standardized contract/engineer management system.',
        'merits.merit3.benefits': 'Minimized risks related to language, culture, and process gaps through platform-based standardization. Flexible engagement models: hire individual engineers, full teams, or request project consulting according to client needs.',
        'challenges.title': 'SKILL BRIDGE Solves the Challenges of Offshore Development',
        'challenges.challenge1.title': 'Offshore development costs...',
        'challenges.challenge1.description': 'Offshore development costs, once an advantage, have become similar to domestic costs due to intermediaries and management fees',
        'challenges.challenge1.solution': 'Achieving Remarkable Cost Performance - SkillBridge aims to restore the cost advantage by providing high quality at reasonable prices in Vietnam',
        'challenges.challenge2.title': 'Communication with foreign engineers...',
        'challenges.challenge2.description': 'Difficulties in smooth communication due to cultural and language differences, leading to delays and quality inconsistencies',
        'challenges.challenge2.solution': 'Japanese BrSEs Ensuring Smooth Progress - Experienced Japanese SEs bridge communication gaps and provide technical/project management',
        'challenges.challenge3.title': 'Concerned about...',
        'challenges.challenge3.description': 'Concerns about the quality of deliverables and the difficulty in selecting reliable offshore development teams/engineers',
        'challenges.challenge3.solution': 'Zero Concerns with Carefully Selected, Trusted Partners - SkillBridge\'s strict selection process for Vietnamese partners, focusing on skills, achievements, and human qualities',
        'solutions.title': 'Solutions',
        'solutions.subtitle': 'Clear Communication, Successful Projects',
        'solutions.subSubtitle': 'Japanese SEs Lead Offshore Development to Success through Direction',
        'solutions.description': 'Communication plays a critical role in system development projects, especially across different languages, cultures, and time zones, to prevent misunderstandings and delays.',
        'solutions.solution1.title': 'Appropriate Task Allocation Based on Technical Understanding',
        'solutions.solution1.description': 'Japanese SE staff ensure accurate task allocation based on technical understanding',
        'solutions.solution2.title': 'Quick Communication Support',
        'solutions.solution2.description': 'Japanese SE staff facilitate quick and accurate communication for smooth project progress',
        'solutions.solution3.title': 'Quality Management and Reviews',
        'solutions.solution3.description': 'Japanese staff participation ensures quality standards and supports continuous improvement',
        'solutions.solution4.title': 'Support for Legal and Contract Procedures',
        'solutions.solution4.description': 'SkillBridge\'s expertise in Vietnam\'s legal system ensures smooth contract procedures',
        'solutions.solution5.title': 'Progress Management with Time Zone Awareness',
        'solutions.solution5.description': 'Time zone differences are managed for efficient task allocation and collaboration',
        'solutions.solution6.title': 'Smooth Project Handover Support',
        'solutions.solution6.description': 'Support for project handover, knowledge transfer, and operation manual preparation',
        'footer.brand.description': 'Connecting talented engineers with companies worldwide',
        'footer.section.legal': 'Legal',
        'footer.section.navigation': 'Navigation',
        'footer.section.contact': 'Contact',
        'footer.links.faq': 'FAQ',
        'footer.links.terms': 'Terms',
        'footer.links.privacy': 'Privacy Policy',
        'footer.services.home': 'HOME',
        'footer.services.engineers': 'List Engineer',
        'footer.services.services': 'Services',
        'footer.services.contact': 'Contact us',
        'footer.contact.email': 'Email',
        'footer.contact.button': 'Get in Touch',
        'footer.copyright': 'All rights reserved',
        // Homepage translations
        'homepage.hero.title': 'SKILL BRIDGE',
        'homepage.hero.subtitle1': 'Connecting talented engineers',
        'homepage.hero.subtitle2': 'with companies worldwide',
        'homepage.hero.description': 'Discover exceptional engineers from Vietnam and around the world. Find the perfect talent for your next project.',
        'homepage.hero.browseEngineers': 'Browse Engineers',
        'homepage.hero.contactUs': 'Contact Us',
        'homepage.statistics.engineers': 'Engineers',
        'homepage.statistics.customers': 'Customers',
        'homepage.howToUse.title': 'How to Use SKILL BRIDGE',
        'homepage.howToUse.step1Title': 'STEP 01: Browse Engineers',
        'homepage.howToUse.step1Desc': 'Explore our database of skilled engineers from various specializations including Web Development, Game Development, and AI/ML.',
        'homepage.howToUse.step2Title': 'STEP 02: Search & Filter',
        'homepage.howToUse.step2Desc': 'Use our advanced search to find engineers matching your requirements by skills, experience, and location.',
        'homepage.howToUse.step3Title': 'STEP 03: Contact Us',
        'homepage.howToUse.step3Desc': 'We will contact you by email within 1 business day, then conduct an online meeting and hearing session.',
        'homepage.categories.web': 'Web development',
        'homepage.categories.game': 'Game development',
        'homepage.categories.aiml': 'AI/ML development',
        'homepage.categories.viewAll': 'View all',
        // Engineer Search Page
        'engineerSearch.pageTitle': 'Find Engineers',
        'engineerSearch.pageDescription': 'Discover skilled engineers available for your projects',
        'engineerSearch.searchPlaceholder': 'Search by name, skill, or keyword...',
        'engineerSearch.advancedSearch': 'Advanced Search',
        'engineerSearch.hideFilters': 'Hide Filters',
        'engineerSearch.filters.title': 'Search Filters',
        'engineerSearch.filters.skills': 'Skills',
        'engineerSearch.filters.seniority': 'Seniority',
        'engineerSearch.filters.location': 'Location',
        'engineerSearch.filters.experience': 'Years of Experience',
        'engineerSearch.filters.salary': 'Salary Range (¥)',
        'engineerSearch.filters.availableOnly': 'Available Only',
        'engineerSearch.filters.resetAll': 'Reset All Filters',
        'engineerSearch.results.searching': 'Searching...',
        'engineerSearch.results.found': 'engineers found',
        'engineerSearch.results.noResults': 'No engineers found matching your criteria.',
        'engineerSearch.results.clearFilters': 'Clear Filters',
        'engineerSearch.pagination.previous': 'Previous',
        'engineerSearch.pagination.next': 'Next',
        'engineerSearch.pagination.page': 'Page',
        'engineerSearch.pagination.of': 'of',
        'engineerSearch.loading': 'Loading...',
        // Engineer Detail Page
        'engineerDetail.listEngineer': 'List engineer',
        'engineerDetail.detail': 'Detail',
        'engineerDetail.title': 'Detail engineer',
        'engineerDetail.overview': 'Overview',
        'engineerDetail.salaryExpectation': 'Salary Expectation',
        'engineerDetail.yearsExperience': 'Years of Experience',
        'engineerDetail.years': 'years',
        'engineerDetail.seniority': 'Seniority',
        'engineerDetail.status': 'Status',
        'engineerDetail.primarySkill': 'Primary Skill',
        'engineerDetail.languages': 'Languages',
        'engineerDetail.skills': 'Skills',
        'engineerDetail.introduction': 'Introduction',
        'engineerDetail.certificates': 'Certificates',
        'engineerDetail.backToList': 'Back to List',
        'engineerDetail.notFound': 'Engineer not found',
        'engineerDetail.loading': 'Loading engineer details...',
        'engineerDetail.status.available': 'Available',
        'engineerDetail.status.busy': 'Busy',
        'engineerDetail.status.notAvailable': 'Not Available',
        // Contact Page
        'contact.title': 'Contact us',
        'contact.description': 'Fill out the form below and we\'ll get back to you within 24 hours.',
        'contact.form.name': 'Name',
        'contact.form.companyName': 'Company name',
        'contact.form.phone': 'Phone',
        'contact.form.email': 'Mail Address',
        'contact.form.title': 'Title',
        'contact.form.message': 'Message',
        'contact.form.required': '*',
        'contact.form.placeholder.name': 'Enter your full name',
        'contact.form.placeholder.companyName': 'Enter your company name',
        'contact.form.placeholder.phone': 'Enter your phone number',
        'contact.form.placeholder.email': 'Enter your email address',
        'contact.form.placeholder.title': 'Enter your request title',
        'contact.form.placeholder.message': 'Enter your message or request details',
        'contact.form.submit': 'Send',
        'contact.form.submitting': 'Sending...',
        'contact.validation.name.required': 'Name is required',
        'contact.validation.name.minLength': 'Name must be at least 2 characters',
        'contact.validation.name.maxLength': 'Name must be less than 100 characters',
        'contact.validation.companyName.required': 'Company name is required',
        'contact.validation.companyName.minLength': 'Company name must be at least 2 characters',
        'contact.validation.companyName.maxLength': 'Company name must be less than 100 characters',
        'contact.validation.phone.required': 'Phone number is required',
        'contact.validation.phone.invalid': 'Please enter a valid phone number',
        'contact.validation.email.required': 'Email is required',
        'contact.validation.email.invalid': 'Please enter a valid email address',
        'contact.validation.title.required': 'Title is required',
        'contact.validation.title.minLength': 'Title must be at least 2 characters',
        'contact.validation.title.maxLength': 'Title must be less than 255 characters',
        'contact.validation.message.required': 'Message is required',
        'contact.validation.message.minLength': 'Message must be at least 10 characters',
        'contact.validation.message.maxLength': 'Message must be less than 1000 characters',
        'contact.error.submit': 'Failed to submit contact form. Please try again.',
        'contact.success.title': 'Thank you for contacting us!',
        'contact.success.description': 'We have received your message and will get back to you within 24 hours.',
        'contact.success.emailSent': 'A confirmation email has been sent to',
        'contact.success.submitAnother': 'Submit Another Request',
        // Client Portal
        'client.header.title.contactManagement': 'Contact management',
        'client.header.title.proposalManagement': 'Proposal management',
        'client.header.title.contractManagement': 'Contract management',
        'client.header.title.dashboard': 'Dashboard',
        'client.sidebar.dashboard': 'Dashboard',
        'client.sidebar.contactForm': 'Contact form',
        'client.sidebar.proposal': 'Proposal',
        'client.sidebar.contract': 'Contract',
        'client.sidebar.logout': 'Logout',
        'client.contactList.search': 'Search',
        'client.contactList.filter.placeholder': 'Filter by status',
        'client.contactList.createNew': 'Create new',
        'client.contactList.table.no': 'No',
        'client.contactList.table.title': 'Title',
        'client.contactList.table.description': 'Description',
        'client.contactList.table.createdOn': 'Created On',
        'client.contactList.table.status': 'Status',
        'client.contactList.table.action': 'Action',
        'client.contactList.status.all': 'All',
        'client.contactList.status.new': 'New',
        'client.contactList.status.converted': 'Converted to Opportunity',
        'client.contactList.status.closed': 'Closed',
        'client.contactList.loading': 'Loading contacts...',
        'client.contactList.noContacts': 'No contacts found',
        'client.contactList.pagination.previous': 'Previous',
        'client.contactList.pagination.next': 'Next',
        // Proposal List
        'client.proposalList.search': 'Search',
        'client.proposalList.filter.placeholder': 'Filter by status',
        'client.proposalList.table.no': 'No',
        'client.proposalList.table.id': 'ID',
        'client.proposalList.table.contactId': 'Contact ID',
        'client.proposalList.table.contactDescription': 'Contact Description',
        'client.proposalList.table.createdOn': 'Created On',
        'client.proposalList.table.status': 'Status',
        'client.proposalList.table.lastUpdated': 'Last Updated',
        'client.proposalList.table.action': 'Action',
        'client.proposalList.status.all': 'All',
        'client.proposalList.status.underReview': 'Under review',
        'client.proposalList.status.requestForChange': 'Request for change',
        'client.proposalList.status.approved': 'Approved',
        'client.proposalList.loading': 'Loading proposals...',
        'client.proposalList.noProposals': 'No proposals found',
        'client.proposalList.pagination.previous': 'Previous',
        'client.proposalList.pagination.next': 'Next',
        // Contract List
        'client.contractList.search.placeholder': 'Search',
        'client.contractList.filter.placeholder': 'Filter by status',
        'client.contractList.filter.all': 'All',
        'client.contractList.filter.active': 'Active',
        'client.contractList.filter.draft': 'Draft',
        'client.contractList.filter.pending': 'Pending',
        'client.contractList.filter.underReview': 'Under Review',
        'client.contractList.filter.requestForChange': 'Request for Change',
        'client.contractList.filter.completed': 'Completed',
        'client.contractList.filter.terminated': 'Terminated',
        'client.contractList.filter.type': 'Type',
        'client.contractList.filter.msa': 'MSA',
        'client.contractList.filter.sow': 'SOW',
        'client.contractList.table.no': 'No',
        'client.contractList.table.id': 'ID',
        'client.contractList.table.contractName': 'Contract Name',
        'client.contractList.table.type': 'Type',
        'client.contractList.table.period': 'Period',
        'client.contractList.table.value': 'Value',
        'client.contractList.table.status': 'Status',
        'client.contractList.table.assignee': 'Assignee',
        'client.contractList.table.action': 'Action',
        'client.contractList.status.active': 'Active',
        'client.contractList.status.draft': 'Draft',
        'client.contractList.status.pending': 'Pending',
        'client.contractList.status.underreview': 'Under Review',
        'client.contractList.status.requestforchange': 'Request for Change',
        'client.contractList.status.completed': 'Completed',
        'client.contractList.status.terminated': 'Terminated',
        'client.contractList.loading': 'Loading contracts...',
        'client.contractList.empty': 'No contracts found',
        'client.createContact.title': 'Create New Contact',
        'client.createContact.titleLabel': 'Title',
        'client.createContact.titlePlaceholder': 'Enter your request title',
        'client.createContact.descriptionLabel': 'Description',
        'client.createContact.descriptionPlaceholder': 'Enter your message or request details',
        'client.createContact.cancel': 'Cancel',
        'client.createContact.save': 'Save Contact',
        'client.createContact.saving': 'Saving...',
        'client.createContact.error.titleRequired': 'Title is required',
        'client.createContact.error.submitFailed': 'Failed to create contact',
        'client.contactDetail.breadcrumb.list': 'Contact Management',
        'client.contactDetail.breadcrumb.detail': 'Consultation Contact',
        'client.contactDetail.title': 'Contact Detail',
        'client.contactDetail.loading': 'Loading contact details...',
        'client.contactDetail.sections.contactInfo': 'Contact Information',
        'client.contactDetail.sections.consultationRequest': 'Consultation Request',
        'client.contactDetail.sections.onlineMeeting': 'Online MTG Link',
        'client.contactDetail.sections.communicationLog': 'Communication Log',
        'client.contactDetail.sections.proposal': 'Proposal',
        'client.contactDetail.fields.contactId': 'Contact ID',
        'client.contactDetail.fields.clientName': 'Client Name',
        'client.contactDetail.fields.phone': 'Phone',
        'client.contactDetail.fields.email': 'Email',
        'client.contactDetail.fields.dateReceived': 'Date Received',
        'client.contactDetail.fields.clientCompany': 'Client Company',
        'client.contactDetail.fields.meetingDate': 'Date and Time',
        'client.contactDetail.fields.meetingLink': 'Link',
        'client.contactDetail.logs.addLog': 'Add Log',
        'client.contactDetail.logs.noLogs': 'No communication logs yet',
        'client.contactDetail.logs.messagePlaceholder': 'Enter communication log message',
        'client.contactDetail.logs.add': 'Add',
        'client.contactDetail.logs.cancel': 'Cancel',
        'client.contactDetail.logs.adding': 'Adding...',
        'client.contactDetail.logs.messageRequired': 'Message is required',
        'client.contactDetail.logs.addFailed': 'Failed to add communication log',
        'client.contactDetail.proposal.approve': 'Approve',
        'client.contactDetail.proposal.comment': 'Comment',
        'client.contactDetail.proposal.approvedAt': 'Approved at',
        'client.contactDetail.comment.title': 'Comment',
        'client.contactDetail.comment.messageLabel': 'Message',
        'client.contactDetail.comment.messagePlaceholder': 'Enter your comment',
        'client.contactDetail.comment.submit': 'Comment',
        'client.contactDetail.comment.submitting': 'Submitting...',
        'client.contactDetail.comment.messageRequired': 'Message is required',
        'client.contactDetail.comment.submitFailed': 'Failed to add comment',
        'client.contactDetail.cancel.title': 'Are you sure to cancel this Consultation?',
        'client.contactDetail.cancel.messageLabel': 'Message',
        'client.contactDetail.cancel.messagePlaceholder': 'Enter reason for cancellation',
        'client.contactDetail.cancel.submit': 'Cancel',
        'client.contactDetail.cancel.cancelling': 'Cancelling...',
        'client.contactDetail.cancel.reasonRequired': 'Reason is required',
        'client.contactDetail.cancel.submitFailed': 'Failed to cancel consultation',
        'client.contactDetail.actions.back': 'Back',
        'client.contactDetail.actions.cancelConsultation': 'Cancel Consultation',
        // Contract Detail
        'client.contractDetail.breadcrumb.list': 'Contract Management',
        'client.contractDetail.breadcrumb.detail': 'Contract detail',
        'client.contractDetail.loading': 'Loading contract details...',
        'client.contractDetail.error.notFound': 'Contract not found',
        'client.contractDetail.error.loadFailed': 'Failed to fetch contract detail',
        'client.contractDetail.sections.overview': 'Overview',
        'client.contractDetail.sections.commercialTerms': 'Commercial Terms',
        'client.contractDetail.sections.legalCompliance': 'Legal / Compliance',
        'client.contractDetail.sections.contacts': 'Contacts',
        'client.contractDetail.sections.history': 'History',
        'client.contractDetail.fields.msaId': 'MSA ID',
        'client.contractDetail.fields.effectiveStart': 'Effective Start',
        'client.contractDetail.fields.effectiveEnd': 'Effective End',
        'client.contractDetail.fields.status': 'Status',
        'client.contractDetail.fields.currency': 'Currency',
        'client.contractDetail.fields.paymentTerms': 'Payment Terms',
        'client.contractDetail.fields.invoicingCycle': 'Invoicing Cycle',
        'client.contractDetail.fields.billingDay': 'Billing Day',
        'client.contractDetail.fields.taxWithholding': 'Tax / Withholding',
        'client.contractDetail.fields.ipOwnership': 'IP Ownership',
        'client.contractDetail.fields.governingLaw': 'Governing Law',
        'client.contractDetail.fields.client': 'Client',
        'client.contractDetail.fields.landbridge': 'LandBridge',
        'client.contractDetail.history.empty': 'No history available',
        'client.contractDetail.actions.approve': 'Approve',
        'client.contractDetail.actions.comment': 'Comment',
        'client.contractDetail.actions.requestForChange': 'Request For Change',
        'client.contractDetail.actions.cancelContract': 'Cancel Contract',
        'client.contractDetail.actions.cancel': 'Cancel',
        'client.contractDetail.actions.processing': 'Processing...',
        'client.contractDetail.approve.confirm': 'Approve Contract',
        'client.contractDetail.approve.confirmMessage': 'Are you sure you want to approve this contract?',
        'client.contractDetail.approve.success': 'Contract approved successfully',
        'client.contractDetail.approve.error': 'Failed to approve contract',
        'client.contractDetail.requestForChange.success': 'Request for change submitted successfully',
        'client.contractDetail.requestForChange.error': 'Failed to submit request for change',
        'client.contractDetail.cancel.title': 'Cancel Contract',
        'client.contractDetail.cancel.reasonLabel': 'Reason',
        'client.contractDetail.cancel.reasonPlaceholder': 'Enter reason for cancellation',
        'client.contractDetail.cancel.submit': 'Cancel Contract',
        'client.contractDetail.cancel.enterReason': 'Enter reason for cancellation:',
        'client.contractDetail.cancel.confirm': 'Are you sure you want to cancel this contract?',
        'client.contractDetail.cancel.success': 'Contract cancelled successfully',
        'client.contractDetail.cancel.error': 'Failed to cancel contract',
        'client.contractDetail.status.active': 'Active',
        'client.contractDetail.status.draft': 'Draft',
        'client.contractDetail.status.pending': 'Pending',
        'client.contractDetail.status.processing': 'Processing',
        'client.contractDetail.status.underReview': 'Under Review',
        'client.contractDetail.status.requestforchange': 'Request for Change',
        'client.contractDetail.status.approved': 'Approved',
        'client.contractDetail.status.completed': 'Completed',
        'client.contractDetail.status.terminated': 'Terminated',
        'client.contractDetail.status.cancelled': 'Cancelled',
        'client.contractDetail.comment.title': 'Request For Change',
        'client.contractDetail.comment.messageLabel': 'Message',
        'client.contractDetail.comment.messagePlaceholder': 'Enter your comment',
        'client.contractDetail.comment.submit': 'Request For Change',
        'client.contractDetail.comment.submitting': 'Submitting...',
        'client.contractDetail.comment.messageRequired': 'Message is required',
        'client.contractDetail.comment.submitFailed': 'Failed to add comment',
        // SOW specific translations
        'client.contractDetail.tabs.contractInfo': 'Contract Info',
        'client.contractDetail.tabs.changeRequests': 'Change Requests',
        'client.contractDetail.fields.sowId': 'SOW ID',
        'client.contractDetail.fields.parentMSA': 'Parent MSA',
        'client.contractDetail.fields.projectName': 'Project Name',
        'client.contractDetail.fields.value': 'Value',
        'client.contractDetail.fields.period': 'Period',
        'client.contractDetail.fields.engagementType': 'Engagement type',
        'client.contractDetail.sections.scopeSummary': 'Scope Summary',
        'client.contractDetail.sections.milestoneDeliverables': 'Milestone Deliverables',
        'client.contractDetail.sections.deliveryItems': 'Delivery Items',
        'client.contractDetail.sections.billingDetails': 'Billing details',
        'client.contractDetail.sections.changeRequest': 'Change Request',
        'client.contractDetail.table.id': 'ID',
        'client.contractDetail.table.milestone': 'Milestone',
        'client.contractDetail.table.deliveryNote': 'Delivery note',
        'client.contractDetail.table.acceptanceCriteria': 'Acceptance Criteria',
        'client.contractDetail.table.plannedEnd': 'Planned End',
        'client.contractDetail.table.paymentPercentage': 'Payment (%)',
        'client.contractDetail.table.billingName': 'Billing name',
        'client.contractDetail.table.amount': 'Amount',
        'client.contractDetail.table.percentage': '%',
        'client.contractDetail.table.invoiceDate': 'Invoice Date',
        'client.contractDetail.table.paymentDate': 'Payment Date',
        'client.contractDetail.table.type': 'Type',
        'client.contractDetail.table.summary': 'Summary',
        'client.contractDetail.table.effectiveFrom': 'Effective from',
        'client.contractDetail.table.effectiveUntil': 'Effective until',
        'client.contractDetail.table.status': 'Status',
        'client.contractDetail.changeRequests.empty': 'No change requests found',
        'client.contractDetail.changeRequests.newChangeRequest': 'New Change Request',
        'client.contractDetail.changeRequests.table.crId': 'CR ID',
        'client.contractDetail.changeRequests.table.type': 'Type',
        'client.contractDetail.changeRequests.table.summary': 'Summary',
        'client.contractDetail.changeRequests.table.effectiveFrom': 'Effective from',
        'client.contractDetail.changeRequests.table.effectiveUntil': 'Effective until',
        'client.contractDetail.changeRequests.table.expectedExtraCost': 'Expected Extra Cost',
        'client.contractDetail.changeRequests.table.costEstimatedByLandbridge': 'Cost Estimated by Landbridge',
        'client.contractDetail.changeRequests.table.status': 'Status',
        'client.contractDetail.changeRequests.table.action': 'Action',
        // Create Change Request Modal
        'client.contractDetail.createChangeRequest.title': 'Create Change Request',
        'client.contractDetail.createChangeRequest.sections.overview': 'Overview',
        'client.contractDetail.createChangeRequest.sections.attachments': 'Attachments',
        'client.contractDetail.createChangeRequest.sections.desiredImpact': 'Desired Impact',
        'client.contractDetail.createChangeRequest.fields.title': 'CR Title',
        'client.contractDetail.createChangeRequest.fields.type': 'CR Type',
        'client.contractDetail.createChangeRequest.fields.description': 'Description',
        'client.contractDetail.createChangeRequest.fields.reason': 'Reason',
        'client.contractDetail.createChangeRequest.fields.desiredStartDate': 'Desired Start Date',
        'client.contractDetail.createChangeRequest.fields.desiredEndDate': 'Desired End Date',
        'client.contractDetail.createChangeRequest.fields.expectedExtraCost': 'Expected Extra Cost',
        'client.contractDetail.createChangeRequest.placeholders.title': 'Enter change request title',
        'client.contractDetail.createChangeRequest.placeholders.type': 'Select CR type',
        'client.contractDetail.createChangeRequest.placeholders.description': 'Enter description of the change request',
        'client.contractDetail.createChangeRequest.placeholders.reason': 'Enter reason for the change request',
        'client.contractDetail.createChangeRequest.placeholders.expectedExtraCost': '¥0',
        'client.contractDetail.createChangeRequest.attachments.uploadText': 'Click or Drag & Drop file here',
        'client.contractDetail.createChangeRequest.buttons.submit': 'Submit Change Request',
        'client.contractDetail.createChangeRequest.buttons.saveDraft': 'Save Draft',
        'client.contractDetail.createChangeRequest.buttons.cancel': 'Cancel',
        'client.contractDetail.createChangeRequest.buttons.submitting': 'Submitting...',
        'client.contractDetail.createChangeRequest.validation.titleRequired': 'CR Title is required',
        'client.contractDetail.createChangeRequest.validation.titleMaxLength': 'CR Title must be 255 characters or less',
        'client.contractDetail.createChangeRequest.validation.typeRequired': 'CR Type is required',
        'client.contractDetail.createChangeRequest.validation.descriptionRequired': 'Description is required',
        'client.contractDetail.createChangeRequest.validation.descriptionMaxLength': 'Description must be 2000 characters or less',
        'client.contractDetail.createChangeRequest.validation.reasonRequired': 'Reason is required',
        'client.contractDetail.createChangeRequest.validation.reasonMaxLength': 'Reason must be 2000 characters or less',
        'client.contractDetail.createChangeRequest.validation.startDateRequired': 'Desired Start Date is required',
        'client.contractDetail.createChangeRequest.validation.endDateRequired': 'Desired End Date is required',
        'client.contractDetail.createChangeRequest.validation.endDateAfterStart': 'End date must be after start date',
        'client.contractDetail.createChangeRequest.validation.costRequired': 'Expected Extra Cost is required',
        'client.contractDetail.createChangeRequest.validation.costPositive': 'Expected Extra Cost must be positive',
        'client.contractDetail.createChangeRequest.validation.fileSize': 'File {fileName} exceeds maximum size of 10MB',
        'client.contractDetail.createChangeRequest.error.submitFailed': 'Failed to create change request',
        'client.contractDetail.createChangeRequest.error.saveDraftFailed': 'Failed to save change request draft',

        // Change Request Detail
        'client.contractDetail.changeRequestDetail.title': 'Change Request Detail',
        'client.contractDetail.changeRequestDetail.loading': 'Loading...',
        'client.contractDetail.changeRequestDetail.sections.overview': 'Overview',
        'client.contractDetail.changeRequestDetail.sections.changeSummary': 'Change Summary',
        'client.contractDetail.changeRequestDetail.sections.evidence': 'Evidence',
        'client.contractDetail.changeRequestDetail.sections.desiredImpact': 'Desired Impact',
        'client.contractDetail.changeRequestDetail.sections.impactAnalysis': 'Impact Analysis by Landbridge',
        'client.contractDetail.changeRequestDetail.sections.history': 'History',
        'client.contractDetail.changeRequestDetail.sections.attachments': 'Attachments',
        'client.contractDetail.changeRequestDetail.fields.crId': 'CR ID',
        'client.contractDetail.changeRequestDetail.fields.crTitle': 'CR Title',
        'client.contractDetail.changeRequestDetail.fields.type': 'Type',
        'client.contractDetail.changeRequestDetail.fields.createdBy': 'Created By',
        'client.contractDetail.changeRequestDetail.fields.createdDate': 'Created Date',
        'client.contractDetail.changeRequestDetail.fields.status': 'Status',
        'client.contractDetail.changeRequestDetail.fields.desiredStartDate': 'Desired Start Date',
        'client.contractDetail.changeRequestDetail.fields.desiredEndDate': 'Desired End Date',
        'client.contractDetail.changeRequestDetail.fields.expectedExtraCost': 'Expected Extra Cost',
        'client.contractDetail.changeRequestDetail.impactAnalysis.devHours': 'Dev Hours',
        'client.contractDetail.changeRequestDetail.impactAnalysis.testHours': 'Test Hours',
        'client.contractDetail.changeRequestDetail.impactAnalysis.newEndDate': 'New End Date',
        'client.contractDetail.changeRequestDetail.impactAnalysis.delayDuration': 'Delay Duration',
        'client.contractDetail.changeRequestDetail.impactAnalysis.additionalCost': 'Additional Cost',
        'client.contractDetail.changeRequestDetail.impactAnalysis.engagedEngineer': 'Engaged Engineer',
        'client.contractDetail.changeRequestDetail.impactAnalysis.billingDetails': 'Billing Details',
        'client.contractDetail.changeRequestDetail.impactAnalysis.engineerLevel': 'Engineer Level',
        'client.contractDetail.changeRequestDetail.impactAnalysis.startDate': 'Start date',
        'client.contractDetail.changeRequestDetail.impactAnalysis.endDate': 'End date',
        'client.contractDetail.changeRequestDetail.impactAnalysis.rating': 'Rating',
        'client.contractDetail.changeRequestDetail.impactAnalysis.salary': 'Salary',
        'client.contractDetail.changeRequestDetail.impactAnalysis.paymentDate': 'Payment Date',
        'client.contractDetail.changeRequestDetail.impactAnalysis.deliveryNote': 'Delivery note',
        'client.contractDetail.changeRequestDetail.impactAnalysis.amount': 'Amount',
        'client.contractDetail.changeRequestDetail.actions.submitChangeRequest': 'Submit Change Request',
        'client.contractDetail.changeRequestDetail.actions.saveDraft': 'Save Draft',
        'client.contractDetail.changeRequestDetail.actions.terminateCR': 'Terminate CR',
        'client.contractDetail.changeRequestDetail.actions.approve': 'Approve',
        'client.contractDetail.changeRequestDetail.actions.requestForChange': 'Request For Change',
        'client.contractDetail.changeRequestDetail.actions.close': 'Close',
        'client.contractDetail.changeRequestDetail.confirm.submit': 'Are you sure you want to submit this change request?',
        'client.contractDetail.changeRequestDetail.confirm.approve': 'Approve Change Request',
        'client.contractDetail.changeRequestDetail.confirm.approveMessage': 'Are you sure you want to approve this change request?',
        'client.contractDetail.changeRequestDetail.confirm.requestForChange': 'Are you sure you want to request for change?',
        'client.contractDetail.changeRequestDetail.confirm.terminate': 'Terminate Change Request',
        'client.contractDetail.changeRequestDetail.confirm.terminateMessage': 'Are you sure you want to terminate this change request? This action cannot be undone.',
        'client.contractDetail.changeRequestDetail.requestForChange.messageLabel': 'Message',
        'client.contractDetail.changeRequestDetail.requestForChange.messagePlaceholder': 'Enter your change request message...',
        'client.contractDetail.changeRequestDetail.actions.cancel': 'Cancel',
        'client.contractDetail.changeRequestDetail.actions.processing': 'Processing...',
        'client.contractDetail.changeRequestDetail.success.update': 'Change request updated successfully',
        'client.contractDetail.changeRequestDetail.success.submit': 'Change request submitted successfully',
        'client.contractDetail.changeRequestDetail.success.approve': 'Change request approved successfully',
        'client.contractDetail.changeRequestDetail.success.requestForChange': 'Change request status updated to Request for Change',
        'client.contractDetail.changeRequestDetail.success.terminate': 'Change request terminated successfully',
        'client.contractDetail.changeRequestDetail.error.updateFailed': 'Failed to update change request',
        'client.contractDetail.changeRequestDetail.error.submitFailed': 'Failed to submit change request',
        'client.contractDetail.changeRequestDetail.error.approveFailed': 'Failed to approve change request',
        'client.contractDetail.changeRequestDetail.error.requestForChangeFailed': 'Failed to request for change',
        'client.contractDetail.changeRequestDetail.error.terminateFailed': 'Failed to terminate change request'
    },
    ja: {
        'navigation.home': 'ホーム',
        'navigation.engineers': 'エンジニア一覧',
        'navigation.services': 'サービス',
        'navigation.contact': 'お問い合わせ',
        'navigation.login': 'ログイン',
        'hero.whatWeDo': '私たちのサービス',
        'hero.ourService': 'サービス',
        'hero.japaneseText1': '信頼できるベトナムオフショア開発パートナーを、',
        'hero.japaneseText2': 'あなたのプロジェクトに。',
        'hero.ctaButton': '開発会社・開発者を探す →',
        'introduction.title': 'SKILL BRIDGE',
        'introduction.subtitle': '日本企業とベトナムIT人材をつなぐ架け橋 課題をサポートするプラットフォーム',
        'introduction.description1': 'SkillBridgeは、ベトナムでのオフショア開発に特化したビジネスマッチングサービスです。日本では、エンジニアの採用がますます困難になり、企業は優秀な人材の確保に苦労しています。',
        'introduction.description2': '経験豊富なベトナム人エンジニアとの協力により、SkillBridgeは高品質なIT人材を大幅なコスト削減で提供します。',
        'introduction.description3': '私たちは、日本企業の深刻なIT人材不足の問題を解決し、グローバル人材との協働が自然なビジネスの一部となる未来を創造することを目指しています。',
        'merits.title': '- メリット -',
        'merits.subtitle': '日本の将来の発展を促進する SKILL BRIDGEが提供する利点',
        'merits.merit1.title': 'トップ人材のアサイン',
        'merits.merit1.description': 'AI、ブロックチェーン、モバイルアプリ開発などの特定分野に特化した高度なスキルを持つエンジニアをアサインできます。',
        'merits.merit1.benefits': '経験豊富な開発者とBrSEを確保することで、スムーズなプロジェクト進行と優れた結果を保証します。',
        'merits.merit2.title': '品質を犠牲にしないコスト効率',
        'merits.merit2.description': '国内開発と比較して大幅なコスト削減（30-50%削減）。',
        'merits.merit2.benefits': '競争力のある価格で高品質な人材にアクセス。明確な契約構造（MSA + サブコントラクト）による透明なコスト管理により、必要に応じてリソースを簡単にスケールできます。',
        'merits.merit3.title': 'スムーズなコミュニケーションと柔軟なエンゲージメント',
        'merits.merit3.description': 'ブリッジSEと標準化された契約/エンジニア管理システムによってサポートされています。',
        'merits.merit3.benefits': 'プラットフォームベースの標準化により、言語、文化、プロセスのギャップに関連するリスクを最小化。柔軟なエンゲージメントモデル：クライアントのニーズに応じて、個別のエンジニア、フルチームの雇用、またはプロジェクトコンサルティングの依頼が可能。',
        'challenges.title': 'SKILL BRIDGEがオフショア開発の課題を解決',
        'challenges.challenge1.title': 'オフショア開発コスト...',
        'challenges.challenge1.description': 'オフショア開発コストは、かつての利点であったにも関わらず、仲介業者や管理費により国内コストと同様になっています',
        'challenges.challenge1.solution': '卓越したコストパフォーマンスの実現 - SkillBridgeは、ベトナムで高品質を合理的な価格で提供することで、コスト優位性を回復することを目指しています',
        'challenges.challenge2.title': '外国人エンジニアとのコミュニケーション...',
        'challenges.challenge2.description': '文化的・言語的差異によるスムーズなコミュニケーションの困難さが、遅延と品質の不整合を引き起こしています',
        'challenges.challenge2.solution': 'スムーズな進行を保証する日本人BrSE - 経験豊富な日本人SEがコミュニケーションギャップを埋め、技術的/プロジェクト管理を提供します',
        'challenges.challenge3.title': '品質への懸念...',
        'challenges.challenge3.description': '成果物の品質保証と信頼できるオフショア開発チーム/エンジニアの選択の困難さへの懸念',
        'challenges.challenge3.solution': '厳選された信頼できるパートナーでゼロ懸念 - SkillBridgeのベトナム人パートナーに対する厳格な選考プロセス、スキル、実績、人間性に焦点を当てています',
        'solutions.title': 'ソリューション',
        'solutions.subtitle': '明確なコミュニケーション、成功するプロジェクト',
        'solutions.subSubtitle': '日本人SEがオフショア開発を成功に導く',
        'solutions.description': 'コミュニケーションは、特に異なる言語、文化、タイムゾーンにわたるシステム開発プロジェクトにおいて、誤解や遅延を防ぐために重要な役割を果たします。',
        'solutions.solution1.title': '技術的理解に基づく適切なタスク配分',
        'solutions.solution1.description': '日本人SEスタッフが技術的理解に基づいて正確なタスク配分を保証します',
        'solutions.solution2.title': '迅速なコミュニケーションサポート',
        'solutions.solution2.description': '日本人SEスタッフがスムーズなプロジェクト進行のための迅速で正確なコミュニケーションを促進します',
        'solutions.solution3.title': '品質管理とレビュー',
        'solutions.solution3.description': '日本人スタッフの参加により品質基準を保証し、継続的改善をサポートします',
        'solutions.solution4.title': '法的・契約手続きのサポート',
        'solutions.solution4.description': 'SkillBridgeのベトナム法制度への専門知識により、スムーズな契約手続きを保証します',
        'solutions.solution5.title': 'タイムゾーンを考慮した進捗管理',
        'solutions.solution5.description': '効率的なタスク配分とコラボレーションのためにタイムゾーンの違いを管理します',
        'solutions.solution6.title': 'スムーズなプロジェクト引き継ぎサポート',
        'solutions.solution6.description': 'プロジェクト引き継ぎ、ナレッジ移転、運用マニュアル作成のサポートを提供します',
        'footer.brand.description': '世界中の優秀なエンジニアと企業をつなぐ',
        'footer.section.legal': '法的情報',
        'footer.section.navigation': 'ナビゲーション',
        'footer.section.contact': 'お問い合わせ',
        'footer.links.faq': 'よくある質問',
        'footer.links.terms': '利用規約',
        'footer.links.privacy': 'プライバシーポリシー',
        'footer.services.home': 'ホーム',
        'footer.services.engineers': 'エンジニア一覧',
        'footer.services.services': 'サービス',
        'footer.services.contact': 'お問い合わせ',
        'footer.contact.email': 'メール',
        'footer.contact.button': 'お問い合わせ',
        'footer.copyright': '全著作権所有',
        // Homepage translations (Japanese)
        'homepage.hero.title': 'SKILL BRIDGE',
        'homepage.hero.subtitle1': '世界中の優秀なエンジニアと',
        'homepage.hero.subtitle2': '企業をつなぐ',
        'homepage.hero.description': 'ベトナムをはじめ、世界中の優れたエンジニアを発見。次のプロジェクトに最適な人材を見つけてください。',
        'homepage.hero.browseEngineers': 'エンジニアを探す',
        'homepage.hero.contactUs': 'お問い合わせ',
        'homepage.statistics.engineers': 'エンジニア',
        'homepage.statistics.customers': '顧客',
        'homepage.howToUse.title': 'SKILL BRIDGEの使い方',
        'homepage.howToUse.step1Title': 'ステップ 01: エンジニアを閲覧',
        'homepage.howToUse.step1Desc': 'Web開発、ゲーム開発、AI/MLなど、様々な専門分野のスキルを持つエンジニアのデータベースをご覧ください。',
        'homepage.howToUse.step2Title': 'ステップ 02: 検索とフィルター',
        'homepage.howToUse.step2Desc': '高度な検索機能を使用して、スキル、経験、場所などの要件に合ったエンジニアを見つけてください。',
        'homepage.howToUse.step3Title': 'ステップ 03: お問い合わせ',
        'homepage.howToUse.step3Desc': '1営業日以内にメールでご連絡し、オンラインミーティングとヒアリングセッションを実施します。',
        'homepage.categories.web': 'Web開発',
        'homepage.categories.game': 'ゲーム開発',
        'homepage.categories.aiml': 'AI/ML開発',
        'homepage.categories.viewAll': 'すべて表示',
        // Engineer Search Page (Japanese)
        'engineerSearch.pageTitle': 'エンジニアを探す',
        'engineerSearch.pageDescription': 'プロジェクトに最適なスキルを持つエンジニアを見つける',
        'engineerSearch.searchPlaceholder': '名前、スキル、またはキーワードで検索...',
        'engineerSearch.advancedSearch': '詳細検索',
        'engineerSearch.hideFilters': 'フィルターを非表示',
        'engineerSearch.filters.title': '検索フィルター',
        'engineerSearch.filters.skills': 'スキル',
        'engineerSearch.filters.seniority': 'レベル',
        'engineerSearch.filters.location': '勤務地',
        'engineerSearch.filters.experience': '経験年数',
        'engineerSearch.filters.salary': '希望給与 (¥)',
        'engineerSearch.filters.availableOnly': '利用可能のみ',
        'engineerSearch.filters.resetAll': 'すべてのフィルターをリセット',
        'engineerSearch.results.searching': '検索中...',
        'engineerSearch.results.found': '人のエンジニアが見つかりました',
        'engineerSearch.results.noResults': '条件に一致するエンジニアが見つかりませんでした。',
        'engineerSearch.results.clearFilters': 'フィルターをクリア',
        'engineerSearch.pagination.previous': '前へ',
        'engineerSearch.pagination.next': '次へ',
        'engineerSearch.pagination.page': 'ページ',
        'engineerSearch.pagination.of': '/',
        'engineerSearch.loading': '読み込み中...',
        // Engineer Detail Page
        'engineerDetail.listEngineer': 'エンジニア一覧',
        'engineerDetail.detail': '詳細',
        'engineerDetail.title': 'エンジニア詳細',
        'engineerDetail.overview': '概要',
        'engineerDetail.salaryExpectation': '希望給与',
        'engineerDetail.yearsExperience': '経験年数',
        'engineerDetail.years': '年',
        'engineerDetail.seniority': 'レベル',
        'engineerDetail.status': 'ステータス',
        'engineerDetail.primarySkill': '主なスキル',
        'engineerDetail.languages': '言語',
        'engineerDetail.skills': 'スキル',
        'engineerDetail.introduction': '自己紹介',
        'engineerDetail.certificates': '資格',
        'engineerDetail.backToList': '一覧に戻る',
        'engineerDetail.notFound': 'エンジニアが見つかりません',
        'engineerDetail.loading': '読み込み中...',
        'engineerDetail.status.available': '対応可能',
        'engineerDetail.status.busy': '対応中',
        'engineerDetail.status.notAvailable': '対応不可',
        // Contact Page (Japanese)
        'contact.title': 'お問い合わせ',
        'contact.description': '以下のフォームにご記入いただくと、24時間以内にご連絡いたします。',
        'contact.form.name': 'お名前',
        'contact.form.companyName': '会社名',
        'contact.form.phone': '電話番号',
        'contact.form.email': 'メールアドレス',
        'contact.form.title': '件名',
        'contact.form.message': 'メッセージ',
        'contact.form.required': '*',
        'contact.form.placeholder.name': 'お名前を入力してください',
        'contact.form.placeholder.companyName': '会社名を入力してください',
        'contact.form.placeholder.phone': '電話番号を入力してください',
        'contact.form.placeholder.email': 'メールアドレスを入力してください',
        'contact.form.placeholder.title': '件名を入力してください',
        'contact.form.placeholder.message': 'メッセージまたはご要望の詳細を入力してください',
        'contact.form.submit': '送信',
        'contact.form.submitting': '送信中...',
        'contact.validation.name.required': 'お名前は必須です',
        'contact.validation.name.minLength': 'お名前は2文字以上である必要があります',
        'contact.validation.name.maxLength': 'お名前は100文字以下である必要があります',
        'contact.validation.companyName.required': '会社名は必須です',
        'contact.validation.companyName.minLength': '会社名は2文字以上である必要があります',
        'contact.validation.companyName.maxLength': '会社名は100文字以下である必要があります',
        'contact.validation.phone.required': '電話番号は必須です',
        'contact.validation.phone.invalid': '有効な電話番号を入力してください',
        'contact.validation.email.required': 'メールアドレスは必須です',
        'contact.validation.email.invalid': '有効なメールアドレスを入力してください',
        'contact.validation.title.required': '件名は必須です',
        'contact.validation.title.minLength': '件名は2文字以上である必要があります',
        'contact.validation.title.maxLength': '件名は255文字以下である必要があります',
        'contact.validation.message.required': 'メッセージは必須です',
        'contact.validation.message.minLength': 'メッセージは10文字以上である必要があります',
        'contact.validation.message.maxLength': 'メッセージは1000文字以下である必要があります',
        'contact.error.submit': 'お問い合わせの送信に失敗しました。もう一度お試しください。',
        'contact.success.title': 'お問い合わせありがとうございます！',
        'contact.success.description': 'お問い合わせを受け付けました。24時間以内にご連絡いたします。',
        'contact.success.emailSent': '確認メールを送信しました',
        'contact.success.submitAnother': '別のお問い合わせを送信',
        // Client Portal (Japanese)
        'client.header.title.contactManagement': 'お問い合わせ管理',
        'client.header.title.proposalManagement': '提案管理',
        'client.header.title.contractManagement': '契約管理',
        'client.header.title.dashboard': 'ダッシュボード',
        'client.sidebar.dashboard': 'ダッシュボード',
        'client.sidebar.contactForm': 'お問い合わせフォーム',
        'client.sidebar.proposal': '提案',
        'client.sidebar.contract': '契約',
        'client.sidebar.logout': 'ログアウト',
        'client.contactList.search': '検索',
        'client.contactList.filter.placeholder': 'ステータスでフィルター',
        'client.contactList.createNew': '新規作成',
        'client.contactList.table.no': '番号',
        'client.contactList.table.title': 'タイトル',
        'client.contactList.table.description': '説明',
        'client.contactList.table.createdOn': '作成日',
        'client.contactList.table.status': 'ステータス',
        'client.contactList.table.action': 'アクション',
        'client.contactList.status.all': 'すべて',
        'client.contactList.status.new': '新規',
        'client.contactList.status.converted': '機会に変換',
        'client.contactList.status.closed': 'クローズ',
        'client.contactList.loading': 'お問い合わせを読み込み中...',
        'client.contactList.noContacts': 'お問い合わせが見つかりません',
        'client.contactList.pagination.previous': '前へ',
        'client.contactList.pagination.next': '次へ',
        // Proposal List (Japanese)
        'client.proposalList.search': '検索',
        'client.proposalList.filter.placeholder': 'ステータスでフィルター',
        'client.proposalList.table.no': '番号',
        'client.proposalList.table.id': 'ID',
        'client.proposalList.table.contactId': 'お問い合わせID',
        'client.proposalList.table.contactDescription': 'お問い合わせ説明',
        'client.proposalList.table.createdOn': '作成日',
        'client.proposalList.table.status': 'ステータス',
        'client.proposalList.table.lastUpdated': '最終更新日',
        'client.proposalList.table.action': 'アクション',
        'client.proposalList.status.all': 'すべて',
        'client.proposalList.status.underReview': 'レビュー中',
        'client.proposalList.status.requestForChange': '変更依頼',
        'client.proposalList.status.approved': '承認済み',
        'client.proposalList.loading': '提案を読み込み中...',
        'client.proposalList.noProposals': '提案が見つかりません',
        'client.proposalList.pagination.previous': '前へ',
        'client.proposalList.pagination.next': '次へ',
        // Contract List (Japanese)
        'client.contractList.search.placeholder': '検索',
        'client.contractList.filter.placeholder': 'ステータスでフィルター',
        'client.contractList.filter.all': 'すべて',
        'client.contractList.filter.active': 'アクティブ',
        'client.contractList.filter.draft': 'ドラフト',
        'client.contractList.filter.pending': '保留中',
        'client.contractList.filter.underReview': 'レビュー中',
        'client.contractList.filter.requestForChange': '変更依頼',
        'client.contractList.filter.completed': '完了',
        'client.contractList.filter.terminated': '終了',
        'client.contractList.filter.type': 'タイプ',
        'client.contractList.filter.msa': 'MSA',
        'client.contractList.filter.sow': 'SOW',
        'client.contractList.table.no': '番号',
        'client.contractList.table.id': 'ID',
        'client.contractList.table.contractName': '契約名',
        'client.contractList.table.type': 'タイプ',
        'client.contractList.table.period': '期間',
        'client.contractList.table.value': '金額',
        'client.contractList.table.status': 'ステータス',
        'client.contractList.table.assignee': '担当者',
        'client.contractList.table.action': 'アクション',
        'client.contractList.status.active': 'アクティブ',
        'client.contractList.status.draft': 'ドラフト',
        'client.contractList.status.pending': '保留中',
        'client.contractList.status.underreview': 'レビュー中',
        'client.contractList.status.requestforchange': '変更依頼',
        'client.contractList.status.completed': '完了',
        'client.contractList.status.terminated': '終了',
        'client.contractList.loading': '契約を読み込み中...',
        'client.contractList.empty': '契約が見つかりませんでした',
        'client.createContact.title': '新規お問い合わせ作成',
        'client.createContact.titleLabel': 'タイトル',
        'client.createContact.titlePlaceholder': '件名を入力してください。',
        'client.createContact.descriptionLabel': '説明',
        'client.createContact.descriptionPlaceholder': 'メッセージまたはご要望の詳細を入力してください。',
        'client.createContact.cancel': 'キャンセル',
        'client.createContact.save': 'お問い合わせを保存',
        'client.createContact.saving': '保存中...',
        'client.createContact.error.titleRequired': 'タイトルは必須です',
        'client.createContact.error.submitFailed': 'お問い合わせの作成に失敗しました',
        'client.contactDetail.breadcrumb.list': 'お問い合わせ管理',
        'client.contactDetail.breadcrumb.detail': '相談お問い合わせ',
        'client.contactDetail.title': 'お問い合わせ詳細',
        'client.contactDetail.loading': 'お問い合わせ詳細を読み込み中...',
        'client.contactDetail.sections.contactInfo': 'お問い合わせ情報',
        'client.contactDetail.sections.consultationRequest': '相談リクエスト',
        'client.contactDetail.sections.onlineMeeting': 'オンラインミーティングリンク',
        'client.contactDetail.sections.communicationLog': 'コミュニケーションログ',
        'client.contactDetail.sections.proposal': '提案',
        'client.contactDetail.fields.contactId': 'お問い合わせID',
        'client.contactDetail.fields.clientName': 'クライアント名',
        'client.contactDetail.fields.phone': '電話番号',
        'client.contactDetail.fields.email': 'メールアドレス',
        'client.contactDetail.fields.dateReceived': '受信日',
        'client.contactDetail.fields.clientCompany': 'クライアント会社',
        'client.contactDetail.fields.meetingDate': '日時',
        'client.contactDetail.fields.meetingLink': 'リンク',
        'client.contactDetail.logs.addLog': 'ログを追加',
        'client.contactDetail.logs.noLogs': 'コミュニケーションログはまだありません',
        'client.contactDetail.logs.messagePlaceholder': 'コミュニケーションログメッセージを入力してください',
        'client.contactDetail.logs.add': '追加',
        'client.contactDetail.logs.cancel': 'キャンセル',
        'client.contactDetail.logs.adding': '追加中...',
        'client.contactDetail.logs.messageRequired': 'メッセージは必須です',
        'client.contactDetail.logs.addFailed': 'コミュニケーションログの追加に失敗しました',
        'client.contactDetail.proposal.approve': '承認',
        'client.contactDetail.proposal.comment': 'コメント',
        'client.contactDetail.proposal.approvedAt': '承認日時',
        'client.contactDetail.comment.title': 'コメント',
        'client.contactDetail.comment.messageLabel': 'メッセージ',
        'client.contactDetail.comment.messagePlaceholder': 'コメントを入力してください',
        'client.contactDetail.comment.submit': 'コメント',
        'client.contactDetail.comment.submitting': '送信中...',
        'client.contactDetail.comment.messageRequired': 'メッセージは必須です',
        'client.contactDetail.comment.submitFailed': 'コメントの追加に失敗しました',
        'client.contactDetail.cancel.title': 'この相談をキャンセルしてもよろしいですか？',
        'client.contactDetail.cancel.messageLabel': 'メッセージ',
        'client.contactDetail.cancel.messagePlaceholder': 'キャンセル理由を入力してください',
        'client.contactDetail.cancel.submit': 'キャンセル',
        'client.contactDetail.cancel.cancelling': 'キャンセル中...',
        'client.contactDetail.cancel.reasonRequired': '理由は必須です',
        'client.contactDetail.cancel.submitFailed': '相談のキャンセルに失敗しました',
        'client.contactDetail.actions.back': '戻る',
        'client.contactDetail.actions.cancelConsultation': '相談をキャンセル',
        // Contract Detail
        'client.contractDetail.breadcrumb.list': '契約管理',
        'client.contractDetail.breadcrumb.detail': '契約詳細',
        'client.contractDetail.loading': '契約詳細を読み込み中...',
        'client.contractDetail.error.notFound': '契約が見つかりません',
        'client.contractDetail.error.loadFailed': '契約詳細の取得に失敗しました',
        'client.contractDetail.sections.overview': '概要',
        'client.contractDetail.sections.commercialTerms': '商業条件',
        'client.contractDetail.sections.legalCompliance': '法的遵守',
        'client.contractDetail.sections.contacts': '連絡先',
        'client.contractDetail.sections.history': '履歴',
        'client.contractDetail.fields.msaId': 'MSA ID',
        'client.contractDetail.fields.effectiveStart': '開始日',
        'client.contractDetail.fields.effectiveEnd': '終了日',
        'client.contractDetail.fields.status': 'ステータス',
        'client.contractDetail.fields.currency': '通貨',
        'client.contractDetail.fields.paymentTerms': '支払条件',
        'client.contractDetail.fields.invoicingCycle': '請求サイクル',
        'client.contractDetail.fields.billingDay': '請求日',
        'client.contractDetail.fields.taxWithholding': '税金/源泉徴収',
        'client.contractDetail.fields.ipOwnership': '知的財産権',
        'client.contractDetail.fields.governingLaw': '準拠法',
        'client.contractDetail.fields.client': 'クライアント',
        'client.contractDetail.fields.landbridge': 'LandBridge',
        'client.contractDetail.history.empty': '履歴がありません',
        'client.contractDetail.actions.approve': '承認',
        'client.contractDetail.actions.comment': 'コメント',
        'client.contractDetail.actions.requestForChange': '変更依頼',
        'client.contractDetail.actions.cancelContract': '契約をキャンセル',
        'client.contractDetail.actions.cancel': 'キャンセル',
        'client.contractDetail.actions.processing': '処理中...',
        'client.contractDetail.approve.confirm': '契約を承認',
        'client.contractDetail.approve.confirmMessage': 'この契約を承認してもよろしいですか？',
        'client.contractDetail.approve.success': '契約が承認されました',
        'client.contractDetail.approve.error': '契約の承認に失敗しました',
        'client.contractDetail.requestForChange.success': '変更依頼が送信されました',
        'client.contractDetail.requestForChange.error': '変更依頼の送信に失敗しました',
        'client.contractDetail.cancel.title': '契約をキャンセル',
        'client.contractDetail.cancel.reasonLabel': '理由',
        'client.contractDetail.cancel.reasonPlaceholder': 'キャンセル理由を入力してください',
        'client.contractDetail.cancel.submit': '契約をキャンセル',
        'client.contractDetail.cancel.enterReason': 'キャンセル理由を入力してください：',
        'client.contractDetail.cancel.confirm': 'この契約をキャンセルしてもよろしいですか？',
        'client.contractDetail.cancel.success': '契約がキャンセルされました',
        'client.contractDetail.cancel.error': '契約のキャンセルに失敗しました',
        'client.contractDetail.status.active': 'アクティブ',
        'client.contractDetail.status.draft': 'ドラフト',
        'client.contractDetail.status.pending': '保留中',
        'client.contractDetail.status.processing': '処理中',
        'client.contractDetail.status.underReview': 'レビュー中',
        'client.contractDetail.status.requestforchange': '変更依頼',
        'client.contractDetail.status.approved': '承認済み',
        'client.contractDetail.status.completed': '完了',
        'client.contractDetail.status.terminated': '終了',
        'client.contractDetail.status.cancelled': 'キャンセル',
        'client.contractDetail.comment.title': '編集の依頼',
        'client.contractDetail.comment.messageLabel': 'メッセージ',
        'client.contractDetail.comment.messagePlaceholder': 'コメントを入力してください',
        'client.contractDetail.comment.submit': '編集の依頼',
        'client.contractDetail.comment.submitting': '送信中...',
        'client.contractDetail.comment.messageRequired': 'メッセージは必須です',
        'client.contractDetail.comment.submitFailed': 'コメントの追加に失敗しました',
        // SOW specific translations (Japanese)
        'client.contractDetail.tabs.contractInfo': '契約情報',
        'client.contractDetail.tabs.changeRequests': '変更依頼',
        'client.contractDetail.fields.sowId': 'SOW ID',
        'client.contractDetail.fields.parentMSA': '親MSA',
        'client.contractDetail.fields.projectName': 'プロジェクト名',
        'client.contractDetail.fields.value': '金額',
        'client.contractDetail.fields.period': '期間',
        'client.contractDetail.fields.engagementType': 'エンゲージメントタイプ',
        'client.contractDetail.sections.scopeSummary': 'スコープ概要',
        'client.contractDetail.sections.milestoneDeliverables': 'マイルストーン成果物',
        'client.contractDetail.sections.deliveryItems': '成果物',
        'client.contractDetail.sections.billingDetails': '請求詳細',
        'client.contractDetail.sections.changeRequest': '変更依頼',
        'client.contractDetail.table.id': 'ID',
        'client.contractDetail.table.milestone': 'マイルストーン',
        'client.contractDetail.table.deliveryNote': '成果物ノート',
        'client.contractDetail.table.acceptanceCriteria': '受入基準',
        'client.contractDetail.table.plannedEnd': '計画終了日',
        'client.contractDetail.table.paymentPercentage': '支払い (%)',
        'client.contractDetail.table.billingName': '請求名',
        'client.contractDetail.table.amount': '金額',
        'client.contractDetail.table.percentage': '%',
        'client.contractDetail.table.invoiceDate': '請求日',
        'client.contractDetail.table.paymentDate': '支払日',
        'client.contractDetail.table.type': 'タイプ',
        'client.contractDetail.table.summary': '概要',
        'client.contractDetail.table.effectiveFrom': '有効開始日',
        'client.contractDetail.table.effectiveUntil': '有効終了日',
        'client.contractDetail.table.status': 'ステータス',
        'client.contractDetail.changeRequests.empty': '変更依頼が見つかりません',
        'client.contractDetail.changeRequests.newChangeRequest': '新規変更依頼',
        'client.contractDetail.changeRequests.table.crId': 'CR ID',
        'client.contractDetail.changeRequests.table.type': 'タイプ',
        'client.contractDetail.changeRequests.table.summary': '概要',
        'client.contractDetail.changeRequests.table.effectiveFrom': '有効開始日',
        'client.contractDetail.changeRequests.table.effectiveUntil': '有効終了日',
        'client.contractDetail.changeRequests.table.expectedExtraCost': '予想追加費用',
        'client.contractDetail.changeRequests.table.costEstimatedByLandbridge': 'Landbridge見積費用',
        'client.contractDetail.changeRequests.table.status': 'ステータス',
        'client.contractDetail.changeRequests.table.action': 'アクション',
        // Create Change Request Modal
        'client.contractDetail.createChangeRequest.title': '変更依頼を作成',
        'client.contractDetail.createChangeRequest.sections.overview': '概要',
        'client.contractDetail.createChangeRequest.sections.attachments': '添付ファイル',
        'client.contractDetail.createChangeRequest.sections.desiredImpact': '希望する影響',
        'client.contractDetail.createChangeRequest.fields.title': 'CRタイトル',
        'client.contractDetail.createChangeRequest.fields.type': 'CRタイプ',
        'client.contractDetail.createChangeRequest.fields.description': '説明',
        'client.contractDetail.createChangeRequest.fields.reason': '理由',
        'client.contractDetail.createChangeRequest.fields.desiredStartDate': '希望開始日',
        'client.contractDetail.createChangeRequest.fields.desiredEndDate': '希望終了日',
        'client.contractDetail.createChangeRequest.fields.expectedExtraCost': '予想追加費用',
        'client.contractDetail.createChangeRequest.placeholders.title': '変更依頼のタイトルを入力',
        'client.contractDetail.createChangeRequest.placeholders.type': 'CRタイプを選択',
        'client.contractDetail.createChangeRequest.placeholders.description': '変更依頼の説明を入力',
        'client.contractDetail.createChangeRequest.placeholders.reason': '変更依頼の理由を入力',
        'client.contractDetail.createChangeRequest.placeholders.expectedExtraCost': '¥0',
        'client.contractDetail.createChangeRequest.attachments.uploadText': 'クリックまたはドラッグ&ドロップでファイルをアップロード',
        'client.contractDetail.createChangeRequest.buttons.submit': '変更依頼を送信',
        'client.contractDetail.createChangeRequest.buttons.saveDraft': '下書きとして保存',
        'client.contractDetail.createChangeRequest.buttons.cancel': 'キャンセル',
        'client.contractDetail.createChangeRequest.buttons.submitting': '送信中...',
        'client.contractDetail.createChangeRequest.validation.titleRequired': 'CRタイトルは必須です',
        'client.contractDetail.createChangeRequest.validation.titleMaxLength': 'CRタイトルは255文字以下である必要があります',
        'client.contractDetail.createChangeRequest.validation.typeRequired': 'CRタイプは必須です',
        'client.contractDetail.createChangeRequest.validation.descriptionRequired': '説明は必須です',
        'client.contractDetail.createChangeRequest.validation.descriptionMaxLength': '説明は2000文字以下である必要があります',
        'client.contractDetail.createChangeRequest.validation.reasonRequired': '理由は必須です',
        'client.contractDetail.createChangeRequest.validation.reasonMaxLength': '理由は2000文字以下である必要があります',
        'client.contractDetail.createChangeRequest.validation.startDateRequired': '希望開始日は必須です',
        'client.contractDetail.createChangeRequest.validation.endDateRequired': '希望終了日は必須です',
        'client.contractDetail.createChangeRequest.validation.endDateAfterStart': '終了日は開始日より後である必要があります',
        'client.contractDetail.createChangeRequest.validation.costRequired': '予想追加費用は必須です',
        'client.contractDetail.createChangeRequest.validation.costPositive': '予想追加費用は正の数である必要があります',
        'client.contractDetail.createChangeRequest.validation.fileSize': 'ファイル {fileName} が最大サイズ10MBを超えています',
        'client.contractDetail.createChangeRequest.error.submitFailed': '変更依頼の作成に失敗しました',
        'client.contractDetail.createChangeRequest.error.saveDraftFailed': '変更依頼の下書き保存に失敗しました',

        // Change Request Detail
        'client.contractDetail.changeRequestDetail.title': '変更依頼詳細',
        'client.contractDetail.changeRequestDetail.loading': '読み込み中...',
        'client.contractDetail.changeRequestDetail.sections.overview': '概要',
        'client.contractDetail.changeRequestDetail.sections.changeSummary': '変更概要',
        'client.contractDetail.changeRequestDetail.sections.evidence': '証拠',
        'client.contractDetail.changeRequestDetail.sections.desiredImpact': '希望する影響',
        'client.contractDetail.changeRequestDetail.sections.impactAnalysis': 'Landbridgeによる影響分析',
        'client.contractDetail.changeRequestDetail.sections.history': '履歴',
        'client.contractDetail.changeRequestDetail.sections.attachments': '添付ファイル',
        'client.contractDetail.changeRequestDetail.fields.crId': 'CR ID',
        'client.contractDetail.changeRequestDetail.fields.crTitle': 'CRタイトル',
        'client.contractDetail.changeRequestDetail.fields.type': 'タイプ',
        'client.contractDetail.changeRequestDetail.fields.createdBy': '作成者',
        'client.contractDetail.changeRequestDetail.fields.createdDate': '作成日',
        'client.contractDetail.changeRequestDetail.fields.status': 'ステータス',
        'client.contractDetail.changeRequestDetail.fields.desiredStartDate': '希望開始日',
        'client.contractDetail.changeRequestDetail.fields.desiredEndDate': '希望終了日',
        'client.contractDetail.changeRequestDetail.fields.expectedExtraCost': '予想追加費用',
        'client.contractDetail.changeRequestDetail.impactAnalysis.devHours': '開発時間',
        'client.contractDetail.changeRequestDetail.impactAnalysis.testHours': 'テスト時間',
        'client.contractDetail.changeRequestDetail.impactAnalysis.newEndDate': '新しい終了日',
        'client.contractDetail.changeRequestDetail.impactAnalysis.delayDuration': '遅延期間',
        'client.contractDetail.changeRequestDetail.impactAnalysis.additionalCost': '追加費用',
        'client.contractDetail.changeRequestDetail.impactAnalysis.engagedEngineer': '従事エンジニア',
        'client.contractDetail.changeRequestDetail.impactAnalysis.billingDetails': '請求詳細',
        'client.contractDetail.changeRequestDetail.impactAnalysis.engineerLevel': 'エンジニアレベル',
        'client.contractDetail.changeRequestDetail.impactAnalysis.startDate': '開始日',
        'client.contractDetail.changeRequestDetail.impactAnalysis.endDate': '終了日',
        'client.contractDetail.changeRequestDetail.impactAnalysis.rating': '評価',
        'client.contractDetail.changeRequestDetail.impactAnalysis.salary': '給与',
        'client.contractDetail.changeRequestDetail.impactAnalysis.paymentDate': '支払日',
        'client.contractDetail.changeRequestDetail.impactAnalysis.deliveryNote': '納品書',
        'client.contractDetail.changeRequestDetail.impactAnalysis.amount': '金額',
        'client.contractDetail.changeRequestDetail.actions.submitChangeRequest': '変更依頼を送信',
        'client.contractDetail.changeRequestDetail.actions.saveDraft': '下書きとして保存',
        'client.contractDetail.changeRequestDetail.actions.terminateCR': 'CRを終了',
        'client.contractDetail.changeRequestDetail.actions.approve': '承認',
        'client.contractDetail.changeRequestDetail.actions.requestForChange': '変更を要求',
        'client.contractDetail.changeRequestDetail.actions.close': '閉じる',
        'client.contractDetail.changeRequestDetail.confirm.submit': 'この変更依頼を送信してもよろしいですか？',
        'client.contractDetail.changeRequestDetail.confirm.approve': '変更依頼を承認',
        'client.contractDetail.changeRequestDetail.confirm.approveMessage': 'この変更依頼を承認してもよろしいですか？',
        'client.contractDetail.changeRequestDetail.confirm.requestForChange': '変更を要求してもよろしいですか？',
        'client.contractDetail.changeRequestDetail.confirm.terminate': '変更依頼を終了',
        'client.contractDetail.changeRequestDetail.confirm.terminateMessage': 'この変更依頼を終了してもよろしいですか？この操作は元に戻せません。',
        'client.contractDetail.changeRequestDetail.requestForChange.messageLabel': 'メッセージ',
        'client.contractDetail.changeRequestDetail.requestForChange.messagePlaceholder': '変更依頼のメッセージを入力してください...',
        'client.contractDetail.changeRequestDetail.actions.cancel': 'キャンセル',
        'client.contractDetail.changeRequestDetail.actions.processing': '処理中...',
        'client.contractDetail.changeRequestDetail.success.update': '変更依頼が正常に更新されました',
        'client.contractDetail.changeRequestDetail.success.submit': '変更依頼が正常に送信されました',
        'client.contractDetail.changeRequestDetail.success.approve': '変更依頼が正常に承認されました',
        'client.contractDetail.changeRequestDetail.success.requestForChange': '変更依頼のステータスが「変更要求」に更新されました',
        'client.contractDetail.changeRequestDetail.success.terminate': '変更依頼が正常に終了されました',
        'client.contractDetail.changeRequestDetail.error.updateFailed': '変更依頼の更新に失敗しました',
        'client.contractDetail.changeRequestDetail.error.submitFailed': '変更依頼の送信に失敗しました',
        'client.contractDetail.changeRequestDetail.error.approveFailed': '変更依頼の承認に失敗しました',
        'client.contractDetail.changeRequestDetail.error.requestForChangeFailed': '変更要求に失敗しました',
        'client.contractDetail.changeRequestDetail.error.terminateFailed': '変更依頼の終了に失敗しました'
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        // Load language from localStorage or default to 'en'
        const savedLanguage = localStorage.getItem('language') as Language;
        if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ja')) {
            setLanguage(savedLanguage);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        const langTranslations = translations[language] as Record<string, string>;
        return langTranslations[key] ?? key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
